import { Product } from "@/types/product";
import { NextResponse } from "next/server";

const products: Product[] = [
  {
    id: 1,
    name: "iPhone 12",
    description: "Latest iPhone model with 5G capability",
    price: 799,
    category: "electronics",
    brand: "apple",
    image: "/products/iphone12.png",
  },
  {
    id: 2,
    name: "Samsung Galaxy S21",
    description: "Flagship Android smartphone with high-end camera",
    price: 799,
    category: "electronics",
    brand: "samsung",
    image: "/products/s21.png",
  },
  {
    id: 3,
    name: "MacBook Air M1",
    description: "Apple M1 chip with 8-core CPU and 7-core GPU",
    price: 999,
    category: "electronics",
    brand: "apple",
    image: "/products/airm1.png",
  },
  {
    id: 4,
    name: "Sony WH-1000XM4",
    description: "Noise-cancelling wireless headphones",
    price: 349,
    category: "audio",
    brand: "sony",
    image: "/products/sonyheadphone.png",
  },
  {
    id: 5,
    name: "Dell XPS 13",
    description: "Ultra-slim laptop with 13-inch display",
    price: 1199,
    category: "computers",
    brand: "dell",
    image: "/products/dellbook.png",
  },
  {
    id: 6,
    name: "PlayStation 5",
    description: "Sony's latest gaming console",
    price: 499,
    category: "gaming",
    brand: "sony",
    image: "/products/ps5.png",
  },
  {
    id: 7,
    name: "Amazon Echo Dot",
    description: "Smart speaker with Alexa",
    price: 49,
    category: "smart home",
    brand: "amazon",
    image: "/products/amazonecho.png",
  },
  {
    id: 8,
    name: "Google Pixel 6",
    description: "Google's latest smartphone with advanced AI",
    price: 699,
    category: "electronics",
    brand: "google",
    image: "/products/googlepixel.png",
  },
  {
    id: 9,
    name: "Bose QuietComfort 45",
    description: "Wireless noise-cancelling headphones",
    price: 329,
    category: "audio",
    brand: "bose",
    image: "/products/headphonebose.png",
  },
  {
    id: 10,
    name: "Fitbit Charge 5",
    description: "Fitness tracker with built-in GPS",
    price: 179,
    category: "wearable",
    brand: "fitbit",
    image: "/products/fitbit.png",
  },
  {
    id: 11,
    name: "Apple Watch Series 7",
    description: "Smartwatch with larger display and fast charging",
    price: 399,
    category: "wearable",
    brand: "apple",
    image: "/products/applewatch7.png",
  },
  {
    id: 12,
    name: "Asus ROG Zephyrus G14",
    description: "Gaming laptop with AMD Ryzen 9 and RTX 3060",
    price: 1599,
    category: "gaming",
    brand: "asus",
    image: "/products/asus.png",
  },
  {
    id: 13,
    name: "LG OLED55C1PUB",
    description: "55-inch OLED 4K TV with AI ThinQ",
    price: 1499,
    category: "electronics",
    brand: "lg",
    image: "/products/lg.png",
  },
  {
    id: 14,
    name: "Razer BlackWidow V3",
    description: "Mechanical gaming keyboard with RGB lighting",
    price: 139,
    category: "gaming",
    brand: "razer",
    image: "/products/keyboard.png",
  },
  {
    id: 15,
    name: "HP Spectre x360",
    description: "2-in-1 laptop with 13.3-inch display",
    price: 1299,
    category: "computers",
    brand: "hp",
    image: "/products/hp.png",
  },
  {
    id: 16,
    name: "DJI Mini 2",
    description: "Foldable drone with 4K camera",
    price: 449,
    category: "drones",
    brand: "dji",
    image: "/products/dji.png",
  },
  {
    id: 17,
    name: "Nikon Z6 II",
    description: "Mirrorless camera with 24.5MP sensor",
    price: 1999,
    category: "cameras",
    brand: "nikon",
    image: "/products/nikon.png",
  },
  {
    id: 18,
    name: "Canon EOS R5",
    description: "Mirrorless camera with 45MP and 8K video",
    price: 3899,
    category: "cameras",
    brand: "canon",
    image: "/products/canon.png",
  },
  {
    id: 19,
    name: "Microsoft Surface Pro 8",
    description: "2-in-1 tablet with 13-inch display",
    price: 1099,
    category: "computers",
    brand: "microsoft",
    image: "/products/surface.png",
  },
  {
    id: 20,
    name: "Sonos One",
    description: "Smart speaker with Alexa and Google Assistant",
    price: 199,
    category: "audio",
    brand: "sonos",
    image: "/products/sonos1.png",
  },
  {
    id: 21,
    name: "Oculus Quest 2",
    description: "All-in-one VR headset with 128GB storage",
    price: 299,
    category: "gaming",
    brand: "oculus",
    image: "/products/vision.png",
  },
  {
    id: 22,
    name: "Ring Video Doorbell 4",
    description: "Smart doorbell with 1080p HD video and two-way talk",
    price: 199,
    category: "smart home",
    brand: "ring",
    image: "/products/ring-video.png",
  },
  {
    id: 23,
    name: "Dyson V11 Torque Drive",
    description: "Cordless vacuum cleaner with powerful suction",
    price: 699,
    category: "home appliances",
    brand: "dyson",
    image: "/products/dyson.png",
  },
  {
    id: 24,
    name: "Apple iPad Pro",
    description: "11-inch iPad Pro with M1 chip",
    price: 799,
    category: "electronics",
    brand: "apple",
    image: "/products/ipad.png",
  },
  {
    id: 25,
    name: "Garmin Fenix 6",
    description: "Multisport GPS watch with heart rate monitor",
    price: 599,
    category: "wearable",
    brand: "garmin",
    image: "/products/watch.png",
  },
  {
    id: 26,
    name: "GoPro HERO9 Black",
    description: "Waterproof action camera with 5K video",
    price: 399,
    category: "cameras",
    brand: "gopro",
    image: "/products/gopro.png",
  },
  {
    id: 27,
    name: "Shure SM7B",
    description: "Dynamic vocal microphone for podcasting and recording",
    price: 399,
    category: "audio",
    brand: "shure",
    image: "/products/shure.png",
  },
  {
    id: 28,
    name: "Anker PowerCore 26800",
    description: "Portable charger with 26800mAh capacity",
    price: 79,
    category: "electronics",
    brand: "anker",
    image: "/products/anker.png",
  },
  {
    id: 29,
    name: "Logitech MX Master 3",
    description: "Wireless mouse with ergonomic design",
    price: 99,
    category: "computers",
    brand: "logitech",
    image: "/products/mouses.png",
  },
  {
    id: 30,
    name: "Tile Mate (2022)",
    description: "Bluetooth tracker for keys and bags",
    price: 24,
    category: "electronics",
    brand: "tile",
    image: "/products/tile.png",
  },
];

export async function GET() {
  return NextResponse.json(products);
}
